apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-app
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  podMetricsEndpoints:
  - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-app
  labels:
    app: frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: web
