apiVersion: v1
kind: Namespace
metadata:
  name: ephemeral-dev-env
---
apiVersion: janitor.mydomain.io/v1alpha1
kind: TTLNamespace
metadata:
  name: clean-dev-env
spec:
  targetNamespace: ephemeral-dev-env
  ttl: "5m"